language: go

go:
  - 1.6
  - tip

sudo: false

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get -t ./...

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci ./...

notifications:
  irc:
    channels:
      - irc.freenode.net#chihaya
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
  email: false
