language: go
go:
  - 1.9.x
sudo: false
matrix:
  include:
  # Using vendored dependencies
  - install:
    - go get -u github.com/golang/dep/...
    - go get -u github.com/golang/lint/...
    - go get -u golang.org/x/tools/cmd/...
    script:
    - dep ensure
    - go test -v $(go list ./...)
    - go vet $(go list ./...)
    - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
    - (for d in $(go list ./...); do diff <(golint $d) <(printf "") || exit 1;  done)
    - go install github.com/chihaya/chihaya/cmd/chihaya
    - chihaya --config=example_config.yaml --debug&
    - pid=$!
    # we move the installation here so chihaya has enough time to start up
    - go install github.com/chihaya/chihaya/cmd/chihaya-e2e
    - chihaya-e2e
    - kill $pid
  # Using HEAD of dependencies
  - install:
    - go get -t ./...
    - go get -u github.com/golang/lint/...
    - go get -u golang.org/x/tools/cmd/...
    script:
    - go test -v $(go list ./...)
    - go vet $(go list ./...)
    - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
    - (for d in $(go list ./...); do diff <(golint $d) <(printf "") || exit 1;  done)
    - go install github.com/chihaya/chihaya/cmd/chihaya
    - chihaya --config=example_config.yaml --debug&
    - pid=$!
    # we move the installation here so chihaya has enough time to start up
    - go install github.com/chihaya/chihaya/cmd/chihaya-e2e
    - chihaya-e2e
    - kill $pid
  allow_failures:
  # Using HEAD of dependencies
  - install:
    - go get -t ./...
    - go get -u github.com/golang/lint/...
    - go get -u golang.org/x/tools/cmd/...
    script:
    - go test -v $(go list ./...)
    - go vet $(go list ./...)
    - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
    - (for d in $(go list ./...); do diff <(golint $d) <(printf "") || exit 1;  done)
    - go install github.com/chihaya/chihaya/cmd/chihaya
    - chihaya --config=example_config.yaml --debug&
    - pid=$!
    # we move the installation here so chihaya has enough time to start up
    - go install github.com/chihaya/chihaya/cmd/chihaya-e2e
    - chihaya-e2e
    - kill $pid
notifications:
  irc:
    channels:
    - irc.freenode.net#chihaya
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
  email: false
