language: go

go: 1.1.2

env:
  - TRAVISCONFIGPATH=/home/travis/gopath/src/github.com/pushrax/chihaya/config/example.json

services:
  - redis-server

notifications:
  irc:
    channels:
      - "irc.freenode.net#chihaya"
    on_success: always
    on_failure: always
