language: go
go:
- 1.6
- tip
sudo: false
install:
- go get -t ./...
script:
- go test -v $(go list ./... | grep -v /vendor/)
notifications:
  irc:
    channels:
    - irc.freenode.net#chihaya
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
  email: false
