language: go

go: 1.2

env:
  - TESTCONFIGPATH=/home/travis/gopath/src/github.com/chihaya/chihaya/config/example.json

services:
  - redis-server

notifications:
  irc:
    channels:
      - "irc.freenode.net#chihaya"
    on_success: always
    on_failure: always
  email: false
