language: go

go: 1.1.2

before_install:
  - sudo apt-get install libzmq3-dev
  - go get -tags zmq_3_x github.com/alecthomas/gozmq

services:
  - redis-server

notifications:
  irc:
    channels:
      - "irc.freenode.net#chihaya"
    on_success: always
    on_failure: always
